In [29]:
import numpy as np
import math
a=np.array([[1,12,123],[123,123,1]])
b=np.array([[7,8,9],[10,11,12]])
c=np.add(a,b)
print("A :",a)
print("\nB :",b)
print("\nAdd :\n",c)
c=np.subtract(a,b)
print("\nSub :",c)
c=np.multiply(a,b)
print("\nMul :",c)

A : [[  1  12 123]
 [123 123   1]]

B : [[ 7  8  9]
 [10 11 12]]

Add :
 [[  8  20 132]
 [133 134  13]]

Sub : [[ -6   4 114]
 [113 112 -11]]

Mul : [[   7   96 1107]
 [1230 1353   12]]


In [24]:
print("A :",a)
c=np.min(a)
print("\nMin :",c)
c=np.min(a,axis=0)
print("\nMinimum elements per column :",c)
c=np.min(a,axis=1)
print("\nMinimum elements per row : ",c)

A : [[1 2 3]
 [4 5 6]]

Min : 1

Minimum elements per column : [1 2 3]

Minimum elements per row :  [1 4]


In [25]:
print("A :",a)
c=np.max(a)
print("\nMax :",c)
c=np.max(a,axis=0)
print("\nMaximum elements per column :",c)
c=np.max(a,axis=1)
print("\nMaximum elements per row : ",c)

A : [[1 2 3]
 [4 5 6]]

Max : 6

Maximum elements per column : [4 5 6]

Maximum elements per row :  [3 6]


In [31]:
print("A :",a)
c=np.average(a)
print("\nAverage :",c)
c=np.mean(a)
print("\nMean :",c)
c=np.mean(a,axis=0)
print("\nMean per column : ",c)
c=np.mean(a,axis=1)
print("\nMean per row : ",c)
c=np.median(a)
print("\nMedian :",c)
c=np.median(a,axis=0)
print("\nMedian per column : ",c)
c=np.median(a,axis=1)
print("\nMedian per row : ",c)
c=np.var(a)
print("\nVariance :",c)
c=np.std(a)
print("\nStandard deviation : ",c)

A : [[  1  12 123]
 [123 123   1]]

Average : 63.833333333333336

Mean : 63.833333333333336

Mean per column :  [62.  67.5 62. ]

Mean per row :  [45.33333333 82.33333333]

Median : 67.5

Median per column :  [62.  67.5 62. ]

Median per row :  [ 12. 123.]

Variance : 3514.138888888889

Standard deviation :  59.280172814263025


In [30]:
#Mean

sum=0
n=0
for i in a:
    for j in i:
        sum+=j
        n+=1
mean=sum/n
print("Mean :",mean)

#Median

sum=0
n=0
for i in range(2):
    sum+=a[i][1]
    n+=1
median=sum/n
print("Meadian : ",median)

#Variance

sum=0
n=0
for i in a:
    for j in i:
        sum+=(j-mean)*(j-mean)
        n+=1
variance=sum/n
print("Variance : ",variance)

#Standard deviation
stddev=math.sqrt(variance)
print("Standard Deviation : ",stddev)

Mean : 63.833333333333336
Meadian :  67.5
Variance :  3514.138888888889
Standard Deviation :  59.280172814263025
