## NUMPY LIBRARY

In [8]:
import numpy as np
a=np.array([1,2,3,4])
print("Creation :",a)
a=np.arange(10)
print("arange : ",a)
a=a.astype(float) # (or)  a.astype(np.float64)
print("Datatype conversion : ",a)

Creation : [1 2 3 4]
arange :  [0 1 2 3 4 5 6 7 8 9]
Datatype conversion :  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [2]:
a=np.array([[6,1,5],[4,3,2]])
print(a)
print("dim : ",a.ndim)
print("row ,columns : ",a.shape)
print("Datatype : ",a.dtype)
a.sort(axis=0)
print("specific sort : ",a)
a.sort()
print("Sorted :",a)

a=a.T
print("Transpose : ",a)

[[6 1 5]
 [4 3 2]]
dim :  2
row ,columns :  (2, 3)
Datatype :  int32
specific sort :  [[4 1 2]
 [6 3 5]]
Sorted : [[1 2 4]
 [3 5 6]]
Reshaping :  [[1 2]
 [4 3]
 [5 6]]
Transpose :  [[1 4 5]
 [2 3 6]]


In [3]:
a=np.zeros([3,4],int)
print("zeros array :\n",a)
a=np.ones([2,3])
print("ones array :\n",a)
a=np.empty([3,2],int)
a.fill(33)
print("Fill : \n",a)
a=np.eye(4,4,dtype=int)
print("Identity :\n",a)

zeros array :
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
ones array :
 [[1. 1. 1.]
 [1. 1. 1.]]
Fill : 
 [[33 33]
 [33 33]
 [33 33]]
Identity :
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [4]:
a=np.linspace(1,30,11,dtype=int)
print(a)

[ 1  3  6  9 12 15 18 21 24 27 30]


In [11]:
a=np.array([[1,4,7],[2,5,8],[3,6,9]])
print("Array :\n",a,"\n......")
print("element at 3rd row 2nd column: ",a[2][1])
b=a[:2,1:]
print("Subarray with upto 2 rows and from 1st column:\n",b)
c=a[:,-2]
print("Negative indexing 2nd last element in each row:",c)

Array :
 [[1 4 7]
 [2 5 8]
 [3 6 9]] 
......
element at 3rd row 2nd column:  6
Subarray with upto 2 rows and from 1st column:
 [[4 7]
 [5 8]]
Negative indexing 2nd last element in each row: [4 5 6]


In [18]:
a=np.array([[1,2,3],[4,5,6]])
print("real :\n",a)
b=a.copy()
print("Copied :\n",b)
c=a.view()
print("View array(changes in original are reflected) :\n",c)
a[1][2]=9
print("after changeing in array 'a' : \n",c)
print("b base :",b.base,"   c base : ",c.base)


real :
 [[1 2 3]
 [4 5 6]]
Copied :
 [[1 2 3]
 [4 5 6]]
View array(changes in original are reflected) :
 [[1 2 3]
 [4 5 6]]
after changeing in array 'a' : 
 [[1 2 3]
 [4 5 9]]
b base : None    c base :  [[1 2 3]
 [4 5 9]]


In [21]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a=a.reshape(3,4)
print("Reshaping : \n",a)
a=a.reshape(2,2,3)
print("3-D reshaping : \n",a)
a=a.reshape(2,3,-1)
print("Unknown reshaping : \n",a)

Reshaping : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3-D reshaping : 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Unknown reshaping : 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [26]:
a=np.array([[[7,8,9],[10,11,12]],[[1,2,3],[4,5,6]]])
for i in a:
    for j in i:
        for k in j:
            print(k)
        print("...")

7
8
9
...
10
11
12
...
1
2
3
...
4
5
6
...


In [49]:
a=np.array([[1,2,3],[7,8,9]])
b=np.array([[4,5,6],[10,11,12]])
print("a : ",a,"\nb : ",b)
c=np.concatenate((a,b))
print("Concatenated array : \n",c)
c=np.concatenate((a,b),axis=1)
print("specific concatenation :\n ",c)
c=np.stack((a,b),axis=0)
print("stack 1 :\n ",c)
c=np.stack((a,b),axis=1)
print("stack 2 :\n ",c)
c=np.stack((a,b),axis=2)
print("stack 3 :\n ",c)
c=np.hstack((a,b))
print("hstack : \n",c)
c=np.vstack((a,b))
print("vstack : \n",c)
c=np.dstack((a,b))
print("dstack : \n",c)

a :  [[1 2 3]
 [7 8 9]] 
b :  [[ 4  5  6]
 [10 11 12]]
Concatenated array : 
 [[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]
specific concatenation :
  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
stack 1 :
  [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
stack 2 :
  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
stack 3 :
  [[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]
hstack : 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
vstack : 
 [[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]
dstack : 
 [[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


In [54]:
a=np.array([1,2,3,4,5,6,2,3])
x=np.where(a==2)
print("indices of 2 :",x)
x=np.where(a%2==0)
print("Even numbers indices: ",x)
a=np.array([4,5,8,9])
x=np.searchsorted(a,8)
print("8 index :",x)
x=np.searchsorted(a,8,side='right')
print("Index of 8 from end :",x)

indices of 2 : (array([1, 6], dtype=int64),)
Even numbers indices:  (array([1, 3, 5, 6], dtype=int64),)
8 index : 2
Index of 8 from end : 3
